"""initial

Revision ID: 68ace575d927
Revises:
Create Date: 2026-06-02 21:43:38.552400

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '68ace575d927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
