"""seed canonical ingredients

Revision ID: h8i9j1k2l3m4
Revises: g7h8i9j1k2l3
Create Date: 2026-06-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op

revision: str = "h8i9j1k2l3m4"
down_revision: Union[str, Sequence[str], None] = "g7h8i9j1k2l3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


INGREDIENTS = [
    "Aubergine",
    "Backpulver",
    "Basilikum",
    "Baumnuss",
    "Bier",
    "Birne",
    "Blattspinat",
    "Blumenkohl",
    "Bohnen",
    "Bouillon",
    "Bratbutter",
    "Brokkoli",
    "Brombeere",
    "Brot",
    "Brot vom Vortag",
    "Butter",
    "Champignons",
    "Chili",
    "Couscous",
    "Cranberry",
    "Curry",
    "Currypulver",
    "Datteln",
    "Dill",
    "Dörrbohnen",
    "Dörrtomaten",
    "Eier",
    "Erbsen",
    "Erdbeere",
    "Erdnussbutter",
    "Essig",
    "Estragon",
    "Feigen",
    "Fenchel",
    "Feta",
    "Frischkäse",
    "Gemüsebouillon",
    "Gewürznelken",
    "Gurke",
    "Haferflocken",
    "Hafermilch",
    "Hackfleisch",
    "Halloumi",
    "Hartkäse",
    "Haselnuss",
    "Hefe",
    "Heidelbeere",
    "Himbeere",
    "Hirse",
    "Honig",
    "Ingwer",
    "Joghurt",
    "Kakaopulver",
    "Kalbfleisch",
    "Kapern",
    "Kardamom",
    "Karotten",
    "Kartoffeln",
    "Käse",
    "Ketchup",
    "Kirschen",
    "Knoblauch",
    "Knollensellerie",
    "Kohlrabi",
    "Kokosmilch",
    "Kokosraspeln",
    "Koriander",
    "Kräuter",
    "Kreuzkümmel",
    "Kürbis",
    "Kurkuma",
    "Lachs",
    "Lauch",
    "Linsen",
    "Lorbeerblatt",
    "Mais",
    "Maisgriess",
    "Maisstärke",
    "Mandeln",
    "Mango",
    "Mascarpone",
    "Mehl",
    "Milch",
    "Milchpulver",
    "Minze",
    "Mozzarella",
    "Muskat",
    "Muskatnuss",
    "Natron",
    "Öl",
    "Oliven",
    "Olivenöl",
    "Orangensaft",
    "Oregano",
    "Paprika",
    "Paprikapulver",
    "Parmesan",
    "Peperoncini",
    "Peperoni",
    "Petersilie",
    "Pfeffer",
    "Pfirsich",
    "Pilze",
    "Pinienkerne",
    "Polenta",
    "Poulet",
    "Pouletbrust",
    "Puderzucker",
    "Quark",
    "Quinoa",
    "Radieschen",
    "Rahm",
    "Randen",
    "Rapsöl",
    "Rapskernöl",
    "Reibkäse",
    "Reis",
    "Ricotta",
    "Rindfleisch",
    "Rohschinken",
    "Rosenkohl",
    "Rosinen",
    "Rosmarin",
    "Rotwein",
    "Ruccola",
    "Rüebli",
    "Safran",
    "Sage",
    "Sahne",
    "Salami",
    "Salat",
    "Salbei",
    "Salz",
    "Sauerrahm",
    "Sbrinz",
    "Schalotten",
    "Schinken",
    "Schlagrahm",
    "Schnittlauch",
    "Schokolade",
    "Schokolade dunkel",
    "Schweinefleisch",
    "Sellerie",
    "Senf",
    "Sesam",
    "Sojasauce",
    "Sonnenblumenkerne",
    "Spargel",
    "Speck",
    "Spinat",
    "Stangensellerie",
    "Süsskartoffeln",
    "Süssrahm",
    "Teigwaren",
    "Thon",
    "Thymian",
    "Tofu",
    "Tomaten",
    "Tomatenmark",
    "Tomatenpüree",
    "Vanille",
    "Vanillezucker",
    "Vollkornmehl",
    "Wasser",
    "Weisswein",
    "Ziegenkäse",
    "Zimt",
    "Zitrone",
    "Zitronensaft",
    "Zucchetti",
    "Zucker",
    "Zwiebel",
]


def upgrade() -> None:
    for name in INGREDIENTS:
        op.execute(
            f"INSERT OR IGNORE INTO ingredients (name) VALUES ('{name}')"
        )


def downgrade() -> None:
    for name in INGREDIENTS:
        op.execute(
            f"DELETE FROM ingredients WHERE name = '{name}'"
        )
